nameOverride: ""
fullnameOverride: ""

nsqd:
  name: "nsqd"
  podDisruptionBudget: {}
    # minAvailable: 1

  service:
    type: ClusterIP
    annotations: {}

  replicaCount: 2
  podManagementPolicy: "Parallel"
  podAnnotations: {}
  updateStrategy: {}
  priorityClassName: ""
  antiAffinity: "soft"
  nodeSelector: {}

  image:
    # Source: https://github.com/nsqio/nsq/blob/master/Dockerfile
    repository: "nsqio/nsq"
    tag: "v1.2.0"
    pullPolicy: "Always"
  extraArgs:
  - --max-msg-timeout=4h
  - --max-req-timeout=3h

  prometheus:
    enabled: false
    image:
      # Because of this issue, we use a fork for 1.1.0: https://github.com/lovoo/nsq_exporter/pull/19
      # Source: https://github.com/emaincourt/nsq_exporter/blob/master/Dockerfile
      repository: emaincourt/nsq_exporter
      tag: latest

  persistence:
    storageClass: ""
    resources:
      requests:
        storage: 1Gi

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

nsqlookupd:
  name: "nsqlookupd"
  replicaCount: 2

  podDisruptionBudget: {}
    # minAvailable: 2

  service:
    annotations: {}
  podManagementPolicy: "Parallel"
  podAnnotations: {}
  # updateStrategy: {}
  # priorityClassName: ""
  antiAffinity: "soft"
  nodeSelector: {}

  image:
    # Source: https://github.com/nsqio/nsq/blob/master/Dockerfile
    repository: "nsqio/nsq"
    tag: "v1.2.0"
    pullPolicy: "Always"
  extraArgs: []

  resources:
    limits:
      cpu: 50m
      memory: 64Mi

nsqadmin:
  enabled: true
  name: "admin"
  auth:
    enabled: false
    username: "admin"
    password: "admin"
    htpasswd:

  autoscaling:
    enabled: false
    annotations: {}
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 60

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      # cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    hosts:
      host: nsq-admin.local
    path: "/"
    tls:
      - hosts:
        - nsq-admin.local
        secretName: nsq-admin-tls

  podDisruptionBudget: {}
    # minAvailable: 1

  service:
    annotations: {}

  replicaCount: 1
  podAnnotations: {}
  # priorityClassName: ""
  # antiAffinity: ""
  nodeSelector: {}

  image:
    # Source: https://github.com/nsqio/nsq/blob/master/Dockerfile
    repository: "nsqio/nsq"
    tag: "v1.2.0"
    pullPolicy: "Always"

  resources:
    limits:
      cpu: 50m
      memory: 32Mi
