apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq-classic.fullname" . }}
  labels:
    {{- include "activemq-classic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8161
      targetPort: 8161
      protocol: TCP
      name: web-console
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
  selector:
    {{- include "activemq-classic.selectorLabels" . | nindent 4 }}
