{{- if and .Values.nsqadmin.auth.enabled .Values.nsqadmin.ingress.enabled -}}
apiVersion: v1
data:
  auth: {{ (htpasswd .Values.nsqadmin.auth.username .Values.nsqadmin.auth.password) | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "nsq.nsqadmin.fullname" . }}-basic-auth
type: Opaque
{{- end }}
