{{- if and .Values.nsqadmin.auth.enabled .Values.nsqadmin.ingress.enabled -}}
apiVersion: v1
data:
  {{- if .Values.nsqadmin.auth.htpasswd }}
  auth: {{ .Values.nsqadmin.auth.htpasswd | b64enc | quote }}
  {{- else }}
  auth: {{ (htpasswd .Values.nsqadmin.auth.username .Values.nsqadmin.auth.password) | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "nsq.nsqadmin.fullname" . }}-basic-auth
type: Opaque
{{- end }}
